id: P42420E49
initial_creation_type: ocr
source_metadata:
  volumes:
    6a7994ef603548dc8cbf52b8ef784015:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་རྡོ་རྗེ་གཅོད་པའི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1682
      volume_number: 56
